config: conf/_XandYtest.yaml
dataset_filesfolder: ./dataset_pendulum
dataset_logger_textfile: dataset_logger_train.txt
dataset_test_logger_textfile: dataset_test_logger.txt
dataset_test_outofdistr_logger_textfile: dataset_test_outofdistr_logger.txt
inherit:
- /Users/aidan/Documents/Code/Work/berkeley/transformer_control/conf/models/standard.yaml
- /Users/aidan/Documents/Code/Work/berkeley/transformer_control/conf/wandb.yaml
loss: mean_squared_error
model:
  family: gpt2
  n_dims: 4
  n_embd: 256
  n_head: 8
  n_layer: 12
  n_positions: 1024
model_logger_textfile: testing.txt
out_dir: ./models/test
pickle_folder: picklefolder
pickle_folder_test: picklefolder_test_indistr
pickle_folder_test_outofdistr: picklefolder_test_outofdistr
test_run: false
training:
  batch_size: 1
  curriculum:
    dims:
      end: 2
      inc: 1
      interval: 200000000
      start: 2
    points:
      end: 1000
      inc: 1
      interval: 2000000000
      start: 300
  data: gaussian
  epochs: 100
  keep_every_steps: 400
  learning_rate: 0.001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 400
  task: linear_regression
  task_kwargs: {}
  test_pendulums: 0
  test_pendulums_outofdistr: 0
  train_steps: 100000
use_chunk: 1
wandb:
  entity: aidansa
  log_every_steps: 100
  name: XandYtest
  notes: CartPole swing-up control with hybrid controller data
  project: cartpole-control
